name: Latest Blog Post Workflow
on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: gautamkrishnar/blog-post-workflow@1.9.7
        with:
          feed_list: "https://dev.to/feed/imranshiundu,https://medium.com/feed/@imranshiundu"
          max_post_count: 5
          dateformat: "MMM DD, YYYY"
          template_post_title: "- [$title]($url) - $date"
          template_section_title: "## Latest Blog Posts"
          post_list_end: "</details>"
          no_item_message: "No blog posts found."
